// <auto-generated />
using CrudWithDb.Src;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudWithDb.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250508191124_addDataTableAllForianKey")]
    partial class addDataTableAllForianKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrudWithDb.Models.Emp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salary")
                        .HasColumnType("int");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Emp");

                    b.HasData(
                        new
                        {
                            id = 1,
                            LanguageId = 1,
                            city = "surat",
                            name = "krunal",
                            salary = 20000,
                            state = "Gujarat"
                        },
                        new
                        {
                            id = 2,
                            LanguageId = 2,
                            city = "gawali",
                            name = "keval",
                            salary = 30000,
                            state = "MP"
                        },
                        new
                        {
                            id = 3,
                            LanguageId = 3,
                            city = "wajipur",
                            name = "samit",
                            salary = 50000,
                            state = "Delhi"
                        },
                        new
                        {
                            id = 4,
                            LanguageId = 1,
                            city = "mumbai",
                            name = "aakash",
                            salary = 60000,
                            state = "maharashtra"
                        });
                });

            modelBuilder.Entity("CrudWithDb.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Indian Language",
                            Title = "Hindi"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "USA Language",
                            Title = "English"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "France Language",
                            Title = "French"
                        });
                });

            modelBuilder.Entity("CrudWithDb.Models.Emp", b =>
                {
                    b.HasOne("CrudWithDb.Models.Language", "Language")
                        .WithMany("EmpList")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("CrudWithDb.Models.Language", b =>
                {
                    b.Navigation("EmpList");
                });
#pragma warning restore 612, 618
        }
    }
}
